### ISSUE TITLE
Can't get HTTPS working on port 443

### ISSUE THREAD

**Issue by pacmac** [OptimalBits/redbird#25] opened 2015-10-21 09:35 UTC
I can't get the reverse proxy on https working at all.

I can start the destination node server on port 443 (instead of 3000)  and it works immediatly, which proves that the https server is working.

But I cannot seem to be able to proxy https requests received on port 443 directed to the destination on 3000.

In your example you used 8080 as listening port, but I believe that the default for https is 443.

	  function sproxy(){
	    var sproxy = require('redbird')({
	      port: 80,
	      ssl: {
	        port: 443,
	        key:  fs.readFileSync('/usr/share/nodejs/ssl/ssl.key'),
	        cert: fs.readFileSync('/usr/share/nodejs/ssl/ssl.crt')
	      }
	    });
	    sproxy.register('mydomain.com', "http://localhost:3000",{ssl: true,});   
	  }

	https.createServer({
	  key:  fs.readFileSync('/usr/share/nodejs/ssl/ssl.key'),
	  cert: fs.readFileSync('/usr/share/nodejs/ssl/ssl.crt')
	},app).listen(3000,function(){
	  
	  sproxy();
	})

**Comment by diginfo** [comment] 2015-10-21 23:20
The web browser connects but just hangs, here's the log files:

	proxy-0 {"name":"redbird","hostname":"DEV","pid":391,"level":50,"err":{"message":"socket hang up","name":"Error","stack":"Error: socket hang up\n    at TLSSocket.<anonymous> (_tls_wrap.js:788:25)\n    at emitOne (events.js:82:20)\n    at TLSSocket.emit (events.js:169:7)\n    at Immediate._onImmediate (net.js:469:12)\n    at processImmediate [as _immediateCallback] (timers.js:374:17)","code":"ECONNRESET"},"msg":"HTTPS Client  Error","time":"2015-10-21T23:17:31.839Z","v":0}
	
	proxy-0 {"name":"redbird","hostname":"DEV","pid":391,"level":50,"err":{"message":"socket hang up","name":"Error","stack":"Error: socket hang up\n    at TLSSocket.<anonymous> (_tls_wrap.js:788:25)\n    at emitOne (events.js:82:20)\n    at TLSSocket.emit (events.js:169:7)\n    at Immediate._onImmediate (net.js:469:12)\n    at processImmediate [as _immediateCallback] (timers.js:374:17)","code":"ECONNRESET"},"msg":"HTTPS Client  Error","time":"2015-10-21T23:17:31.843Z","v":0}

**Comment by manast** [comment] 2015-10-22 06:19
can you copy the proxy code that you are creating on a gist so that I can take a look at it?

**Comment by diginfo** [comment] 2015-10-22 08:01
Hi, this is the code:

	var fs = require('fs');
	
	var proxy = require('redbird')({
	  port: 80,
	  ssl: {
	    port:443,
	    key:  fs.readFileSync('/usr/share/nodejs/ssl/ssl.key'),
	    cert: fs.readFileSync('/usr/share/nodejs/ssl/ssl.crt'),
	    ca: fs.readFileSync('/usr/share/nodejs/ssl/sub.class1.server.ca.pem')
	  }
	});
	
	
	var routes = {
		'dev.xxx.com': {host:'localhost',port:3002},
	 	'update.xxx.com': {host:'localhost',port:1000},
	 	'beta.xxx.com': {host:'localhost',port:3001},
	}
	
	for(var r in routes){
		proxy.register(r,'http://'+routes[r].host+':'+routes[r].port,{ssl:true});	
	}
	
	
	//keep alive forever
	require('net').createServer().listen();

**Comment by diginfo** [comment] 2015-10-22 08:28
I would actually prefer that only the proxy server uses https when communicating with the client, and the connection from the proxy to the destination server uses regular http.

I tried setting {ssl:false} during route registration, but this made no difference.

**Comment by pacmac** [comment] 2015-10-23 02:41
Hi;

Any news on this ?

**Comment by manast** [comment] 2015-10-23 22:43
sorry for the delay in answering this, I will you a proper answer during the weekend

**Comment by diginfo** [comment] 2015-10-24 07:19
Thanks, as I am not having any success at all.

**Comment by manast** [comment] 2015-10-24 17:56
Ok, I will try to understand in order. First to @pacman.
The code you posted refers to mydomain.com, how are you testing this code? Can you just use this route and test on the localhost instead?
```
sproxy.register('mydomain.com', "http://localhost:3000", {ssl: true,}); 
```
also since you are using port 80 and 443 you need to start the proxy with sudo.

**Comment by manast** [comment] 2015-10-24 18:00
@pacmac your code seems correct. the communication between the proxy and the backend servers is using http. I am not sure why you put this line at the end:
```
//keep alive forever
require('net').createServer().listen();
```
should not be needed.

**Comment by manast** [comment] 2015-10-24 18:02
What version of node are you using?

**Comment by diginfo** [comment] 2015-10-25 00:51
Hi;

1) O/S & Node version is Ubuntu 14.04/64 - 0.10.40
2) require('net').createServer().listen(); was just a generic keep-alive code that I use to keep a script alive forever.
3) Node is already running as root
4) redbird http works no problem
5) http-proxy and bounce both work with https, no problem

**Comment by manast** [comment] 2015-10-25 09:08
what kind of certificate are you using? wildcard?
can you change your route registration code to this one:
```
for(var r in routes){
    proxy.register(r,'http://'+routes[r].host+':'+routes[r].port, {
      ssl:true
      key:  fs.readFileSync('/usr/share/nodejs/ssl/ssl.key'),
      cert: fs.readFileSync('/usr/share/nodejs/ssl/ssl.crt'),
      ca: fs.readFileSync('/usr/share/nodejs/ssl/sub.class1.server.ca.pem')
   });   
}
```
This will enable SNI for every registered route. If you are not using a wildcard certificate you need to have a different certificate for every route you register.


Regarding the keep alive method you are using, as far as I know that kind of patterns are not needed on node.

**Comment by diginfo** [comment] 2015-10-25 09:59
I don't think this is related to the certs as I am able to use the same certs to enable https on individual node servers and I can connect to them without using redbird.

I am also use the same certs with bouncy and http-roxy and the certs and proxy forwarding is 100% working on both bouncy and http-node but not on redbird.

I have also made a direct copy of your example https code which is on github readme, and using that code I also CANNOT connect.

var redbird = new require('redbird')({
    port: 8080,

    // Specify filenames to default SSL certificates (in case SNI is not supported by the 
    // user's browser)
    ssl: {
        port: 8443,
        key: "certs/dev-key.pem",
        cert: "certs/dev-cert.pem",
    }
});

// Since we will only have one https host, we dont need to specify additional certificates.
redbird.register('some-domain-of-mine', 'http://localhost:8082', {ssl: true});

**Comment by manast** [comment] 2015-10-25 10:08
Actually, you need a certificate for every domain, it does not matter if you are using one host or several. Thats the whole point of SNI…

> On 25 Oct 2015, at 10:59, diginfo <notifications@github.com> wrote:
> 
> I don't think this is related to the certs as I am able to use the same certs to enable https on individual node servers and I can connect to them without using redbird.
> 
> I am also use the same certs with bouncy and http-roxy and the certs and proxy forwarding is 100% working on both bouncy and http-node but not on redbird.
> 
> I have also made a direct copy of your example https code which is on github readme, and using that code I also CANNOT connect.
> 
> var redbird = new require('redbird')({
> port: 8080,
> 
> // Specify filenames to default SSL certificates (in case SNI is not supported by the 
> // user's browser)
> ssl: {
>     port: 8443,
>     key: "certs/dev-key.pem",
>     cert: "certs/dev-cert.pem",
> }
> });
> 
> // Since we will only have one https host, we dont need to specify additional certificates.
> redbird.register('some-domain-of-mine', 'http://localhost:8082', {ssl: true});
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/OptimalBits/redbird/issues/25#issuecomment-150907973>.
> 

Manuel Astudillo, M.Sc.C.E
CEO, founder.

OptimalBits
Ideon Science Park
Scheelevägen 15
SE-22370, Lund. Sweden.
mobile:+46 (0) 733 329536
Skype: manast76
twitter/manast <http://twitter.com/manast>

www.optimalbits.com <http://www.optimalbits.com/>

**Comment by diginfo** [comment] 2015-10-25 10:14
This has nothing to do with the certs, I have official comodo wildcard signed certs *.domain.name (https://ssl.comodo.com/wildcard-ssl-certificates.php) and these certs work fine with other proxy servers.

I can use the same certs with http-proxy (https://github.com/nodejitsu/node-http-proxy) and bouncy (https://github.com/substack/bouncy) and also use the certs on a node server that does not use redbird and the certs work fine.

**Comment by manast** [comment] 2015-10-25 10:20
Ok, so you are using a wildcard certificate. I asked that before, since it is important for the setup.
I will try the example in the README, to see if for some reason it is not working.
Redbird is of course used in production, not only by us but many other users, so something is not correct in your setup, or something is triggering a bug in redbird that specific for your setup.

**Comment by diginfo** [comment] 2015-10-25 11:53
Thanks

But I have spent several days trying to get https to work, I have been using Redbirds http successfully for a few months.

But I just can't spend any more time on this, so are now using http-proxy instead which I was able to get to work almost on the first attempt

Thanks any way for your help, you can close this issue, I won't be needing Redbirds now

**Closed** 2015-10-25 13:08 UTC

**Comment by diginfo** [comment] 2015-10-26 06:31
FYI, I believe this is the same issue: https://github.com/OptimalBits/redbird/issues/17

**Comment by manast** [comment] 2015-10-26 08:09
Ok. I think I know what the problem is then...

**Comment by diginfo** [comment] 2015-11-09 09:14
"Ok. I think I know what the problem is then..."

Is this likely to get fixed ?

**Comment by manast** [comment] 2015-11-09 10:03
It is fixed already, check the issue ;)
